name: Checks

on:
  workflow_call:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  checks:
    name: Run Checks
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: hehe
        run: |
          cargo build

      # - name: Install tools
      #   uses: taiki-e/install-action@v2
      #   with:
      #     tool: cargo-llvm-cov

      # - name: Run checks
      #   shell: bash
      #   run: ./scripts/checks.sh

      # - name: Upload coverage to Codecov
      #   if: success()
      #   uses: codecov/codecov-action@v5
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./cobertura.xml
      #     fail_ci_if_error: true
      #     slug: avocado-linux/prserv
